name: Kimono
version: '${project.version}'
main: shx.kimono.Kimono
author: Shiro Interactive
description: Scripting plugin for Shiro Interactive Server
website: https://shiro.eu.org
api-version: '1.20'
load: POSTWORLD
commands:
  kimono:
    description: Kimono
